connectando o db
brunoSpeedrun/bff-github-users pull request #8
Opened 2020-05-05 20:32 UTC by augustoOliveira-1993

2020-05-05 20:41 UTC, brunoSpeedrun requested changes
- Não vamos utilizar o **package-lock.json** pois estamos utilizando o yarn.

- O Arquivo **.env** deve ser adicionado ao .gitignore.

2020-05-06 21:15 UTC, alanlins commented on src/mongoose/mongoose.module.ts
> +// import { Module } from '@nestjs/common';
Pode deletar esse arquivo e pasta, pois está comentado.
Ou pode recortar a mesma lógica que está no app.module.ts para este arquivo, e usar o MongooseModule no lugar dele.

2020-05-06 21:21 UTC, alanlins commented
Uma dica, sempre antes de fazer o commit, executar o comando yarn lint e yarn format.
Pra verificar e formatar a organização do código.

2020-05-07 11:52 UTC, brunoSpeedrun approved these changes

2020-05-07 11:52 UTC, merged